#Default port is 5555
server:
  port: 5555
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: "*"

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    onlinedogshowservice: /ods/**
    dogservice: /dog/**
    judgeservice: /judge/**
    showservice: /show/**
    lofselectclubservice: /lofselectclub/**
  debug:
    request: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.scc: DEBUG

        